### ISSUE TITLE
Make work with django 3.2.4

### ISSUE THREAD

**Issue by cviveiro** [MetLifeLegalPlans/zygoat#150]
```
backend_1        | ModuleNotFoundError: No module named 'zygoat'
backend_1        | 
backend_1        | During handling of the above exception, another exception occurred:
backend_1        | 
backend_1        | Traceback (most recent call last):
backend_1        |   File "/code/./manage.py", line 22, in <module>
backend_1        |     main()
backend_1        |   File "/code/./manage.py", line 18, in main
backend_1        |     execute_from_command_line(sys.argv)
backend_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
backend_1        |     utility.execute()
backend_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
backend_1        |     django.setup()
backend_1        |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
backend_1        |     apps.populate(settings.INSTALLED_APPS)
backend_1        |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
backend_1        |     app_config = AppConfig.create(entry)
backend_1        |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 246, in create
backend_1        |     raise ImproperlyConfigured(
backend_1        | django.core.exceptions.ImproperlyConfigured: Cannot import 'zygoat'. Check that 'willing_zg.apps.ZygoatConfig.name' is correct.
```
happens with django 3.2.4, doesn't with django 3.1.12. maybe this: https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery? but haven't looked into it deeply.

**Comment by markrawls** [comment]
On Django 3.2.5 we've got absolutely no issue with this - potentially an issue on `django-willing-zg`? Will attempt to reproduce.
